/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "the-red.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Ack, Ack, AUTO)


PB_BIND(Nack, Nack, AUTO)


PB_BIND(InitFromApp, InitFromApp, AUTO)


PB_BIND(InitFromGuitar, InitFromGuitar, AUTO)


PB_BIND(ReqInitFromGuitar, ReqInitFromGuitar, AUTO)


PB_BIND(ChangeGuitarName, ChangeGuitarName, AUTO)


PB_BIND(TunerOnOff, TunerOnOff, AUTO)


PB_BIND(TunerFrequency, TunerFrequency, AUTO)


PB_BIND(KnobClicked, KnobClicked, AUTO)


PB_BIND(KnobMatchingStart, KnobMatchingStart, AUTO)


PB_BIND(BatteryLevel, BatteryLevel, AUTO)


PB_BIND(ParamGate, ParamGate, AUTO)


PB_BIND(ParamEfxTs90, ParamEfxTs90, AUTO)


PB_BIND(ParamEfxSd10, ParamEfxSd10, AUTO)


PB_BIND(ParamEfxRat, ParamEfxRat, AUTO)


PB_BIND(ParamEfxDistortion, ParamEfxDistortion, AUTO)


PB_BIND(ParamEfxAutowah, ParamEfxAutowah, AUTO)


PB_BIND(ParamEfxAcoustic, ParamEfxAcoustic, AUTO)


PB_BIND(ParamAmpFd, ParamAmpFd, AUTO)


PB_BIND(ParamAmpMs, ParamAmpMs, AUTO)


PB_BIND(ParamAmpMsbg, ParamAmpMsbg, AUTO)


PB_BIND(ParamAmpVx, ParamAmpVx, AUTO)


PB_BIND(ParamAmpBgn, ParamAmpBgn, AUTO)


PB_BIND(ParamCabA, ParamCabA, AUTO)


PB_BIND(ParamCabB, ParamCabB, AUTO)


PB_BIND(ParamCabC, ParamCabC, AUTO)


PB_BIND(ParamCabD, ParamCabD, AUTO)


PB_BIND(ParamCabE, ParamCabE, AUTO)


PB_BIND(ParamModChorus, ParamModChorus, AUTO)


PB_BIND(ParamModTremolo, ParamModTremolo, AUTO)


PB_BIND(ParamModPhaser, ParamModPhaser, AUTO)


PB_BIND(ParamModVibrato, ParamModVibrato, AUTO)


PB_BIND(ParamDelayDelay, ParamDelayDelay, AUTO)


PB_BIND(ParamReverb, ParamReverb, AUTO)


PB_BIND(CategoryData, CategoryData, AUTO)


PB_BIND(BankData, BankData, 2)


PB_BIND(KnobMatching, KnobMatching, 2)


PB_BIND(InitKnobMatching1, InitKnobMatching1, 2)


PB_BIND(InitKnobMatching2, InitKnobMatching2, 2)


PB_BIND(InitKnobMatching3, InitKnobMatching3, 2)


PB_BIND(KnobMatchingAll, KnobMatchingAll, 2)


PB_BIND(ClearEffects, ClearEffects, AUTO)


PB_BIND(SingleParam, SingleParam, AUTO)


PB_BIND(DiagReq, DiagReq, AUTO)


PB_BIND(DiagRespPOC, DiagRespPOC, AUTO)


PB_BIND(DiagRespFirstParing, DiagRespFirstParing, AUTO)


PB_BIND(DiagRespErrCode, DiagRespErrCode, AUTO)


PB_BIND(BulkIrStartReq, BulkIrStartReq, AUTO)


PB_BIND(BulkIrReq, BulkIrReq, AUTO)


PB_BIND(BulkIrEndReq, BulkIrEndReq, AUTO)


PB_BIND(BulkIrRes, BulkIrRes, AUTO)


PB_BIND(ReqDisconnect, ReqDisconnect, AUTO)


PB_BIND(ReqGuitarName, ReqGuitarName, AUTO)


PB_BIND(ResGuitarName, ResGuitarName, AUTO)


PB_BIND(ReqPlayPairingSound, ReqPlayPairingSound, AUTO)


PB_BIND(ReqBootloadMode, ReqBootloadMode, AUTO)


PB_BIND(ReqIsBootloadMode, ReqIsBootloadMode, AUTO)


PB_BIND(ResIsBootloadMode, ResIsBootloadMode, AUTO)


PB_BIND(ParamAmpClean, ParamAmpClean, AUTO)


PB_BIND(ParamAmpClean2, ParamAmpClean2, AUTO)


PB_BIND(ParamAmpClean3, ParamAmpClean3, AUTO)


PB_BIND(ParamAmpClean4, ParamAmpClean4, AUTO)


PB_BIND(ParamAmpClean5, ParamAmpClean5, AUTO)


PB_BIND(ParamAmpClean6, ParamAmpClean6, AUTO)


PB_BIND(ParamAmpClean7, ParamAmpClean7, AUTO)















