/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "the-red.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Ack, Ack, AUTO)


PB_BIND(Nack, Nack, AUTO)


PB_BIND(ReqSetupInfo, ReqSetupInfo, AUTO)


PB_BIND(FirstContact, FirstContact, AUTO)


PB_BIND(FirstContactResp, FirstContactResp, AUTO)


PB_BIND(ChangeGuitarName, ChangeGuitarName, AUTO)


PB_BIND(TunerOnOff, TunerOnOff, AUTO)


PB_BIND(TunerFrequency, TunerFrequency, AUTO)


PB_BIND(KnobClicked, KnobClicked, AUTO)


PB_BIND(KnobMatchingStart, KnobMatchingStart, AUTO)


PB_BIND(EffectEod, EffectEod, AUTO)


PB_BIND(BatteryLevel, BatteryLevel, AUTO)


PB_BIND(CurrentKnobSelected, CurrentKnobSelected, AUTO)


PB_BIND(SelectGate, SelectGate, AUTO)


PB_BIND(SelectEfx, SelectEfx, AUTO)


PB_BIND(SelectAmp, SelectAmp, AUTO)


PB_BIND(SelectIr, SelectIr, AUTO)


PB_BIND(SelectMod, SelectMod, AUTO)


PB_BIND(SelectDelay, SelectDelay, AUTO)


PB_BIND(SelectReverb, SelectReverb, AUTO)


PB_BIND(ParamGateNoiseGate, ParamGateNoiseGate, AUTO)


PB_BIND(ParamGateLimiter, ParamGateLimiter, AUTO)


PB_BIND(ParamGateCompressor, ParamGateCompressor, AUTO)


PB_BIND(ParamEfxOverdrive, ParamEfxOverdrive, AUTO)


PB_BIND(ParamEfxDistortion, ParamEfxDistortion, AUTO)


PB_BIND(ParamEfxFuzz, ParamEfxFuzz, AUTO)


PB_BIND(ParamEfxBitCrusher, ParamEfxBitCrusher, AUTO)


PB_BIND(ParamAmpFender, ParamAmpFender, AUTO)


PB_BIND(ParamAmpMarshall, ParamAmpMarshall, AUTO)


PB_BIND(ParamAmpVox, ParamAmpVox, AUTO)


PB_BIND(ParamAmpAcoustic, ParamAmpAcoustic, AUTO)


PB_BIND(ParamIrFender, ParamIrFender, AUTO)


PB_BIND(ParamIrMarshall, ParamIrMarshall, AUTO)


PB_BIND(ParamIrVox, ParamIrVox, AUTO)


PB_BIND(ParamIrAcoustic, ParamIrAcoustic, AUTO)


PB_BIND(ParamModFlange, ParamModFlange, AUTO)


PB_BIND(ParamModChorus, ParamModChorus, AUTO)


PB_BIND(ParamModTremolo, ParamModTremolo, AUTO)


PB_BIND(ParamModPhaser, ParamModPhaser, AUTO)


PB_BIND(ParamModVibrato, ParamModVibrato, AUTO)


PB_BIND(ParamDelayEcho, ParamDelayEcho, AUTO)


PB_BIND(ParamDelayDelay, ParamDelayDelay, AUTO)


PB_BIND(ParamReverbRoom, ParamReverbRoom, AUTO)


PB_BIND(ParamReverbHall, ParamReverbHall, AUTO)


PB_BIND(ParamReverbPlate, ParamReverbPlate, AUTO)


PB_BIND(ParamReverbSpring, ParamReverbSpring, AUTO)


PB_BIND(DiagReq, DiagReq, AUTO)


PB_BIND(DiagRespPOC, DiagRespPOC, AUTO)


PB_BIND(DiagRespFirstParing, DiagRespFirstParing, AUTO)


PB_BIND(DiagRespErrCode, DiagRespErrCode, AUTO)


PB_BIND(bulkIrStartReq, bulkIrStartReq, AUTO)


PB_BIND(bulkIrReq, bulkIrReq, AUTO)


PB_BIND(bulkIrEndReq, bulkIrEndReq, AUTO)


PB_BIND(bulkIrRes, bulkIrRes, AUTO)














