/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "the-red.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Ack, Ack, AUTO)


PB_BIND(Nack, Nack, AUTO)


PB_BIND(InitFromApp, InitFromApp, AUTO)


PB_BIND(InitFromGuitar, InitFromGuitar, AUTO)


PB_BIND(ChangeGuitarName, ChangeGuitarName, AUTO)


PB_BIND(TunerOnOff, TunerOnOff, AUTO)


PB_BIND(TunerFrequency, TunerFrequency, AUTO)


PB_BIND(KnobClicked, KnobClicked, AUTO)


PB_BIND(KnobMatchingStart, KnobMatchingStart, AUTO)


PB_BIND(BatteryLevel, BatteryLevel, AUTO)


PB_BIND(CurrentKnobSelected, CurrentKnobSelected, AUTO)


PB_BIND(ParamGate, ParamGate, 2)


PB_BIND(ParamEfxOverdrive, ParamEfxOverdrive, AUTO)


PB_BIND(ParamEfxDistortion, ParamEfxDistortion, AUTO)


PB_BIND(ParamEfxFuzz, ParamEfxFuzz, AUTO)


PB_BIND(ParamEfxAcoustic, ParamEfxAcoustic, AUTO)


PB_BIND(ParamAmpF, ParamAmpF, AUTO)


PB_BIND(ParamAmpMa, ParamAmpMa, AUTO)


PB_BIND(ParamAmpMe, ParamAmpMe, AUTO)


PB_BIND(ParamAmpV, ParamAmpV, AUTO)


PB_BIND(ParamAmpB, ParamAmpB, AUTO)


PB_BIND(ParamCabA, ParamCabA, AUTO)


PB_BIND(ParamCabB, ParamCabB, AUTO)


PB_BIND(ParamCabC, ParamCabC, AUTO)


PB_BIND(ParamCabD, ParamCabD, AUTO)


PB_BIND(ParamCabE, ParamCabE, AUTO)


PB_BIND(ParamModFlange, ParamModFlange, AUTO)


PB_BIND(ParamModChorus, ParamModChorus, AUTO)


PB_BIND(ParamModTremolo, ParamModTremolo, AUTO)


PB_BIND(ParamModPhaser, ParamModPhaser, AUTO)


PB_BIND(ParamModVibrato, ParamModVibrato, AUTO)


PB_BIND(ParamDelayDelay, ParamDelayDelay, AUTO)


PB_BIND(ParamReverbRoom, ParamReverbRoom, AUTO)


PB_BIND(ParamReverbHall, ParamReverbHall, AUTO)


PB_BIND(ParamReverbPlate, ParamReverbPlate, AUTO)


PB_BIND(ParamReverbSpring, ParamReverbSpring, AUTO)


PB_BIND(DiagReq, DiagReq, AUTO)


PB_BIND(DiagRespPOC, DiagRespPOC, AUTO)


PB_BIND(DiagRespFirstParing, DiagRespFirstParing, AUTO)


PB_BIND(DiagRespErrCode, DiagRespErrCode, AUTO)


PB_BIND(BulkIrStartReq, BulkIrStartReq, AUTO)


PB_BIND(BulkIrReq, BulkIrReq, AUTO)


PB_BIND(BulkIrEndReq, BulkIrEndReq, AUTO)


PB_BIND(BulkIrRes, BulkIrRes, AUTO)







