class EffectorStructure {
  late Categories categories;

  Categories makeEffectorStructure() {
    categories = Categories(categories: [
      Category(name: "Gate", effectors: [
        Effector(name: "Gate", params: [
          Param(
              name: "noiseGateThreshold",
              UIname: "Noise Gate Threshold",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "noiseGateOpeningTime",
              UIname: "Noise Gate Opening Time",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 10,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "noiseGateClosingTime",
              UIname: "Noise Gate Closing Time",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 10,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "noiseGateHoldTime",
              UIname: "Noise Gate Hold Time",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 10,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "compressorAttack",
              UIname: "Compressor Attack",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "compressorRelease",
              UIname: "Compressor Release",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "compressorGain",
              UIname: "Compressor Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 30,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "compressorHysteresis",
              UIname: "Compressor Hysteresis",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 10,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "autowahDepth",
              UIname: "Autowah Depth",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "autowahMix",
              UIname: "Autowah Mix",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 100,
              step: 1,
              unit: "",
              logScale: false),
        ]),
      ], isOn: false),
      Category(name: "EFX", effectors: [
        Effector(name: "Overdrive", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "Tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false)
        ]),
        Effector(name: "Distortion", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "Tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false)
        ]),
        Effector(name: "Fuzz", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "Tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "Acoustic", params: [
          Param(
              name: "bass",
              UIname: "Bass",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "middle",
              UIname: "Middle",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "treble",
              UIname: "Treble",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
        ])

      ], isOn: false,
      ), Category(name: "Amp", effectors: [
        Effector(name: "F", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "bass",
              UIname: "Bass",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "middle",
              UIname: "Middle",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "treble",
              UIname: "Treble",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "Ma", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "bass",
              UIname: "Bass",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "middle",
              UIname: "Middle",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "treble",
              UIname: "Treble",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "Me", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "bass",
              UIname: "Bass",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "middle",
              UIname: "Middle",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "treble",
              UIname: "Treble",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "V", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "bass",
              UIname: "Bass",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "middle",
              UIname: "Middle",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "treble",
              UIname: "Treble",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "B", params: [
          Param(
              name: "gain",
              UIname: "Gain",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "bass",
              UIname: "Bass",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "middle",
              UIname: "Middle",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "treble",
              UIname: "Treble",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 50,
              step: 1,
              unit: "",
              logScale: false),
        ]),
      ], isOn: false),
      Category(name: "Cab", effectors: [
        Effector(name: "A", params: [
          Param(
              name: "level",
              UIname: "LEVEL",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "B", params: [
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "C", params: [
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "D", params: [
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "E", params: [
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
        ]),
      ], isOn: false),
      Category(name: "Mod", effectors: [
        Effector(name: "Flange", params: [
          Param(
              name: "manual",
              UIname: "Manual",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "depth",
              UIname: "Depth",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "rate",
              UIname: "Rate",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: true),
        ]),
        Effector(name: "Chorus", params: [
          Param(
              name: "rate",
              UIname: "Rate",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: false),
        ]),
        Effector(name: "Tremolo", params: [
          Param(
              name: "depth",
              UIname: "Depth",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "rate",
              UIname: "Rate",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 30,
              step: 1,
              unit: "",
              logScale: true),
        ]),
        Effector(name: "Phaser", params: [
          Param(
              name: "rate",
              UIname: "Rate",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "depth",
              UIname: "Depth",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: true),
        ]),
        Effector(name: "Vibrato", params: [
          Param(
              name: "rate",
              UIname: "Rate",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 30,
              step: 1,
              unit: "",
              logScale: true),
          Param(
              name: "depth",
              UIname: "Depth",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 40,
              step: 1,
              unit: "",
              logScale: false),
        ])
      ], isOn: false),
      Category(name: "Delay", effectors: [
        Effector(name: "Delay", params: [
          Param(
              name: "time",
              UIname: "Time",
              min: 0,
              max: 1000,
              type: "int",
              paramDefault: 300,
              step: 1,
              unit: "ms",
              logScale: false),
          Param(
              name: "feedback",
              UIname: "Feedback",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "level",
              UIname: "Level",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: true),
        ]),
      ], isOn: false),
      Category(name: "Reverb", effectors: [
        Effector(name: "Room", params: [
          Param(
              name: "roomsize",
              UIname: "Room Size",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "mix",
              UIname: "Mix",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: true),
        ]),
        Effector(name: "Hall", params: [
          Param(
              name: "roomsize",
              UIname: "Room Size",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "mix",
              UIname: "Mix",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: true),
        ]),
        Effector(name: "Plate", params: [
          Param(
              name: "roomsize",
              UIname: "Room Size",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "mix",
              UIname: "Mix",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: true),
        ]),
        Effector(name: "Spring", params: [
          Param(
              name: "roomsize",
              UIname: "Room Size",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 20,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "tone",
              UIname: "tone",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 60,
              step: 1,
              unit: "",
              logScale: false),
          Param(
              name: "mix",
              UIname: "Mix",
              min: 0,
              max: 100,
              type: "int",
              paramDefault: 80,
              step: 1,
              unit: "",
              logScale: true),
        ]),
      ], isOn: false)
    ]);

    return categories;
  }
}


class Categories {
  late List<Category> categories;
  late List<bool> onOffs;

  Categories({
    required this.categories,
  });

}

class Category {
  late String name;
  late List<Effector> effectors;
  late bool isOn;

  Category({required this.name, required this.effectors, required this.isOn});
}

class Effector {
  late String name;
  late List<Param> params;

  Effector({
    required this.name,
    required this.params,
  });

}

class Param {
  late String name;
  late String? UIname;
  late int? min;
  late int? max;
  late String? type;
  late int paramDefault;
  late int? step;
  late String? unit;
  late bool? logScale;

  Param({
    required this.name,
    this.UIname,
    this.min,
    this.max,
    this.type,
    required this.paramDefault,
    this.step,
    this.unit,
    this.logScale,
  });
}


